apiVersion: v1
kind: ConfigMap
metadata:
  name: frontconfig
data:
  nginx.conf: |-
    server {
      root /build;
      error_page  404 index.html;
      location / {
        try_files $uri $uri/ /index.html;
      }
    }
