apiVersion: v1
kind: ConfigMap
metadata:
  name: frontconfig
data:
  nginx.conf: |-
    server {
      error_page  404 /index.html;
      location / {
        index index.html;
        try_files $uri $uri/ /index.html;
      }
    }
