apiVersion: v1
kind: ConfigMap
metadata:
  name: frontconfig
data:
  nginx.conf: |-
    server {
      error_page  404 /build/index.html;
      location / {
        try_files $uri $uri/ /build/index.html;
      }
    }
