apiVersion: v1
kind: ConfigMap
metadata:
  name: frontconfig
  namespace: default
data:
  nginx.conf: |-
    http {
      server {
        location / {
          try_files $uri $uri/ /index.html;
        }
      }
    }
