apiVersion: v1
kind: ConfigMap
metadata:
  name: frontconfig
data:
  nginx.conf: |-
    server {
      location / {
        if (!-e $request_filename){
          rewrite ^(.*)$ /index.html break;
        }
      }
    }
